# Generated by Django 3.2.16 on 2022-10-30 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recipe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name_plural': 'Recipies'},
        ),
    ]
